services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./admin:/app/admin
      - /app/admin/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
